### PR TITLE
Preview parameter for using preview API endpoint

### PR DESCRIPTION
**Pull request by neonichu**
This makes it easier to use the Contentful [preview API](https://www.contentful.com/blog/2014/09/23/preview-your-content-before-publishing-with-the-content-preview-api/).

BTW, thanks for building this :tada:

### CODE REVIEW

**Comment by ryan-codingintrigue** [comment]
Looks great, thanks a lot for contributing!

**Comment by dibble-james** [comment]
Hi guys, is this likely to make it into an update to the Nuget package sometime?  I'll also reiterate the thanks for building this!

**Comment by ryan-codingintrigue** [comment]
@dibble-james Yeah I totally forgot to update the Nuget package. It's even still in Prerelease!

New version should now be available

**Comment by dibble-james** [comment]
Got it, working great thanks!

**Pull request merged**
